server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/ead-authuser
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


